package mime

const (
	AAC    = "audio/aac"                                                                 //AAC audio
	ABW    = "application/x-abiword"                                                     //AbiWord document
	ARC    = "application/x-freearc"                                                     //Archive document (multiple files embedded)
	AVI    = "video/x-msvideo"                                                           //AVI: Audio Video Interleave
	AZW    = "application/vnd.amazon.ebook"                                              //Amazon Kindle eBook format
	BIN    = "application/octet-stream"                                                  //Any kind of binary data
	BMP    = "image/bmp"                                                                 //Windows OS/2 Bitmap Graphics
	BZ     = "application/x-bzip"                                                        //BZip archive
	BZ2    = "application/x-bzip2"                                                       //BZip2 archive
	CSH    = "application/x-csh"                                                         //C-Shell script
	CSS    = "text/css"                                                                  //Cascading Style Sheets (CSS)
	CSV    = "text/csv"                                                                  //Comma-separated values (CSV)
	DOC    = "application/msword"                                                        //Microsoft Word
	DOCX   = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"   //Microsoft Word (OpenXML)
	EOT    = "application/vnd.ms-fontobject"                                             //MS Embedded OpenType fonts
	EPUB   = "application/epub+zip"                                                      //Electronic publication (EPUB)
	GZ     = "application/gzip"                                                          //GZip Compressed Archive
	GIF    = "image/gif"                                                                 //Graphics Interchange Format (GIF)
	HTML   = "text/html"                                                                 //HyperText Markup Language (HTML)
	ICO    = "image/vnd.microsoft.icon"                                                  //Icon format
	ICS    = "text/calendar"                                                             //iCalendar format
	JAR    = "application/java-archive"                                                  //Java Archive (JAR)
	JPEG   = "image/jpeg"                                                                //JPEG images
	JS     = "text/javascript"                                                           //text/javascript, per the following specifications:
	JSON   = "application/json"                                                          //JSON format
	JSONLD = "application/ld+json"                                                       //JSON-LD format
	MID    = "audio/midi"                                                                //Musical Instrument Digital Interface (MIDI)
	MIDI   = "audio/x-midi"                                                              //Musical Instrument Digital Interface (MIDI)
	MJS    = "text/javascript"                                                           //JavaScript module
	MP3    = "audio/mpeg"                                                                //MP3 audio
	CDA    = "application/x-cdf"                                                         //CD audio
	MP4    = "video/mp4"                                                                 //MP4 audio
	MPEG   = "video/mpeg"                                                                //MPEG Video
	MPKG   = "application/vnd.apple.installer+xml"                                       //Apple Installer Package
	ODP    = "application/vnd.oasis.opendocument.presentation"                           //OpenDocument presentation document
	ODS    = "application/vnd.oasis.opendocument.spreadsheet"                            //OpenDocument spreadsheet document
	ODT    = "application/vnd.oasis.opendocument.text"                                   //OpenDocument text document
	OGA    = "audio/ogg"                                                                 //OGG audio
	OGV    = "video/ogg"                                                                 //OGG video
	OGX    = "application/ogg"                                                           //OGG
	OPUS   = "audio/opus"                                                                //Opus audio
	OTF    = "font/otf"                                                                  //OpenType font
	PNG    = "image/png"                                                                 //Portable Network Graphics
	PDF    = "application/pdf"                                                           //Adobe Portable Document Format (PDF)
	PHP    = "application/x-httpd-php"                                                   //Hypertext Preprocessor (Personal Home Page)
	PPT    = "application/vnd.ms-powerpoint"                                             //Microsoft PowerPoint
	PPTX   = "application/vnd.openxmlformats-officedocument.presentationml.presentation" //Microsoft PowerPoint (OpenXML)
	RAR    = "application/vnd.rar"                                                       //RAR archive
	RTF    = "application/rtf"                                                           //Rich Text Format (RTF)
	SH     = "application/x-sh"                                                          //Bourne shell script
	SVG    = "image/svg+xml"                                                             //Scalable Vector Graphics (SVG)
	SWF    = "application/x-shockwave-flash"                                             //Small web format (SWF) or Adobe Flash document
	TAR    = "application/x-tar"                                                         //Tape Archive (TAR)
	TIFF   = "image/tiff"                                                                //Tagged Image File Format (TIFF)
	TS     = "video/mp2t"                                                                //MPEG transport stream
	TTF    = "font/ttf"                                                                  //TrueType Font
	TXT    = "text/plain"                                                                //Text, (generally ASCII or ISO 8859-n)
	VSD    = "application/vnd.visio"                                                     //Microsoft Visio
	WAV    = "audio/wav"                                                                 //Waveform Audio Format
	WEBA   = "audio/webm"                                                                //WEBM audio
	WEBM   = "video/webm"                                                                // 	WEBM video
	WEBP   = "image/webp"                                                                //WEBP image
	WOFF   = "font/woff"                                                                 //Web Open Font Format (WOFF)
	WOFF2  = "font/woff2"                                                                //Web Open Font Format (WOFF)
	XHTML  = "application/xhtml+xml"                                                     //XHTML
	XLS    = "application/vnd.ms-excel"                                                  //Microsoft Excel
	XLSX   = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"         //Microsoft Excel (OpenXML)
	XML    = "application/xml"                                                           //XML
	TXML   = "text/xml"                                                                  //XML
	XUL    = "application/vnd.mozilla.xul+xml"                                           //XUL
	ZIP    = "application/zip"                                                           //ZIP archive
	V3GP   = "video/3gpp"                                                                //video container
	A3GP   = "audio/3gpp"                                                                //audio container
	V3G2   = "video/3gpp2"                                                               //video container
	A3G2   = "audio/3gpp2"                                                               //audio container
	X7Z    = "application/x-7z-compressed"                                               //7-zip archive
)
